### ISSUE TITLE
Setup fails after update from 4.2.7 to 4.3.0 or 4.3.2

### ISSUE THREAD

**Issue by Duncan1106** [BJReplay/ha-solcast-solar#264]
#### This bug report requests debug logs.  If you don't provide them don't expect any help, unless you are an expert developer and know why they're not required.  And, if you're an expert developer, know that they're not required, and you're wrong, don't expect any help.

Note the instructions for getting debug logs, and follow them.

#### Fill in **all** of the data requested.

By failing to provide debug logs, you're providing us with permission to ignore you, or, at best, say debug logs required, and then ignore you.  By being lazy and not bothering to fill in data, you're encouraging us to be lazy and not bother responding.

## Describe the bug

After updating from 4.2.7 to 4.3.2 the setup fails with following error:

```
Logger: homeassistant.config_entries
Source: config_entries.py:753
First occurred: 11:49:23 (2 occurrences)
Last logged: 11:49:56

Error setting up entry Solcast Solar for solcast_solar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/__init__.py", line 287, in async_setup_entry
    await solcast.get_sites_and_usage()
  File "/config/custom_components/solcast_solar/solcastapi.py", line 888, in get_sites_and_usage
    remove_orphans(multi_key_sites, multi_sites)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 829, in remove_orphans
    component_parts.group(1) + "******" + component_parts.group(2)[:6] + component_parts.group(3),
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

## Logs
```
2025-04-02 11:58:01.061 DEBUG (MainThread) [custom_components.solcast_solar] Auto-update options: {'auto_update': 1}
2025-04-02 11:58:01.061 DEBUG (MainThread) [custom_components.solcast_solar] Estimate to use options: {'key_estimate': 'estimate'}
2025-04-02 11:58:01.061 DEBUG (MainThread) [custom_components.solcast_solar] Attribute options: {'attr_brk_detailed': False, 'attr_brk_estimate': False, 'attr_brk_estimate10': True, 'attr_brk_estimate90': True, 'attr_brk_halfhourly': True, 'attr_brk_hourly': True, 'attr_brk_site': True}
2025-04-02 11:58:01.061 DEBUG (MainThread) [custom_components.solcast_solar] Custom sensor options: {'customhoursensor': 1}
2025-04-02 11:58:01.061 DEBUG (MainThread) [custom_components.solcast_solar] Hard limit: {'hard_limit_api': '100.0'}
2025-04-02 11:58:01.063 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Configuration directory is /config
2025-04-02 11:58:01.063 DEBUG (MainThread) [custom_components.solcast_solar] Session headers: {'Accept': 'application/json', 'User-Agent': 'ha-solcast-solar-integration/4.3'}
2025-04-02 11:58:01.111 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Solcast Solar for solcast_solar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 753, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/__init__.py", line 287, in async_setup_entry
    await solcast.get_sites_and_usage()
  File "/config/custom_components/solcast_solar/solcastapi.py", line 888, in get_sites_and_usage
    remove_orphans(multi_key_sites, multi_sites)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/solcastapi.py", line 829, in remove_orphans
    component_parts.group(1) + "******" + component_parts.group(2)[:6] + component_parts.group(3),
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

## To Reproduce

Updated, restart as requested from Homeassistant and then it failed

I confirm:

- [✅] I have attached **debug** logs
- [✅] I have embedded **debug** logs in the issue description (enclosed in tick marks ``` for proper formatting)
- [ ] Confirmed **debug** logs are not required for this issue

Make sure you include logs from HA listing the output from the Solcast integration showing the error - this is particularly useful in debugging issues and helping to determine whether the issue is with the integration or the Solcast service

## Solcast Integration Version

- Integration Version [4.3.2]

## Additional context

I did a rolback to 4.3.0 add it happens there too, same error, a rollback to 4.2.7 works for me.
Have i done anything wrong in the setup?

**Comment by autoSteve** [comment]
An interesting issue, @Duncan1106. And thanks for the logs. This error should not cause a catastrophic failure of the integration. That it does is my bad as it's just clean-up activities.

It is likely that those code lines were introduced in v4.3.0. I've not double-checked, though.

These in `solcastapi.py`:

``` python
        remove_orphans(multi_key_sites, multi_sites)
        remove_orphans(multi_key_usage, multi_usage)
```

Their purpose is to clean up any orphaned cache files where a change from multiple API keys has occurred. (Has this ever occurred for you?)

Could you have a look at the content of `/config`, AKA `/homeassistant` for the `solcast*` files that exist there. If you are using one API key these will be named like `solcast-sites.json`, or if using multiple API keys like `solcast-sites-MYAPIKEYHERE.json`. Delete any cache files there that do not make sense given your configuration (after backing them up) and re-start the v4.3.x integration.

Please don't disclose your API key in any response here.

**Comment by autoSteve** [comment]
Alternatively rename the nonsensical cache files to `.json.old`...

**Comment by autoSteve** [comment]
A theory that I have is that these code lines have "always" been erroring for you in the past (even using v4.2.7), but just being logged. One of the changes that occurred in v4.3.0 was the removal of several `try`/`except` blocks that catch and deal with code errors.

The reason for removal is that I basically wanted to expose any of these "passive" errors that didn't kill the integration so that they might be properly dealt with. The PyTest code developed caught many, but PyTest is only as good as the tests it is instructed to do. I may have missed something.

I believe that you've just earned a spotters award for finding a latent issue that I've missed.

Sadly there is no prize.

**Comment by Duncan1106** [comment]
Thank you very much that did it! 
I had a third solcast-sites-third-api-key.json and solcast-usage-third-api-key.json file that i didnt use anymore, so after removing them and updating to 4.3.2 all is working now.

Thank you for the very fast and precise help from you and also a big THANKS for such an awesome Integration 😄

**Comment by autoSteve** [comment]
Brilliant. This is interesting, and disturbing as well @Duncan1106. It deserves a code fix and a bug label.

Talk me through this.

Any orphaned API key cache files should be removed (and logged as having been removed) so this failure is a clear code issue. Albeit for a very small cohort.

What was the sequence? You set up with three API keys, and then removed one at some point?

**Comment by Duncan1106** [comment]
Originally I had only one API key, then we had another solar system installed and I adjusted to having two different API keys.

After that we installed a third small solar system and I tried solcast for that too, but it was too inaccurate so I removed it using the configure button, just leaving the other two keys in, that's basically it.

**Comment by autoSteve** [comment]
Simple enough. Thanks!

I shall build a PyTest scenario to mimick that behaviour, as this should definitely not cause the "magic smoke" to come out of the integration.

Out of interest, why two API keys, and not two Solcast sites for the one API key? Also out of interest, did you get to the bottom of why Solcast was not accurate for the third system?

**Comment by Duncan1106** [comment]
I wanted to have more API Requests per site so I used the two accounts for one solar system each.
I'm limited to 10 per account...

It wanted to add a solar system with 820W and Solcast can't add any systems under 1000W so I got around that limitation adjusted all values by multiplying with 10 and just wanted to divide all values by 10 afterwards using templates where I needed it. 

That didn't work out great...
I compared to the forecast.solar integration and the actual values of the system and it was like 0.5 to 1 kwh off each time, which in this scale is way to much, considering at great days, no clouds it produces around 3.8 to max 4.3 kWh...

Maybe there is something wrong with the way I think the forecasting works or simply the fact that the smaller the system gets the more inaccurate it gets to predict, I don't know.

**Comment by autoSteve** [comment]
More forecast updates doesn't generally equal more quality, but I get your motivation. Ten API calls per day per site for free is pretty stingy, but Soldast do make their brilliant services free for hobbyists, and that is most welcome. They are usually great, and far better than forecast.solar. No forecast is 100%, or we'd all be winning the football tips and raking in much money...

Site set-up is most significant. With azimuth/tilt key. It may be that you got that wrong, or it may be that Solcast did get it wrong. 🫢 But that is by the by. It's a forecast.

Thanks for the brilliant feedback, which will ensure that this forecasting integration works better in future!

**Comment by autoSteve** [comment]
I worked out why this failed. I believe the orphaned API key contained a non-alphanumberic character, almost certainly an underscore.

**Comment by autoSteve** [comment]
I had a think about the whole array < 1kW thing, @Duncan1106 (which is a bit bizarre). What if you messed with the efficiency percentage? That probably linerarly reduces the forecasted panel output, so maybe with things set up as a 1kW system you could set 82% efficient and see what the forecasts look like...

**Comment by Duncan1106** [comment]
Thanks ill try tonight and report back if i see the any meaningful accuracy. 
Also here is the old api key, i regenerated it, so that should be fine:


`TuWp12pVZ2yy8bB33BqrCb7pgk--_n6X`


hopefully that helps and confirms your findings.

**Comment by autoSteve** [comment]
Yep. Thurrs ya problem! Hyphens and underscores, so the linked PR will fix the issue for any who would have hit this again in future.

**Comment by autoSteve** [comment]
This is absolutely confirmed, however it has exposed another weakness, so thanks for sharing the actual old key. Logging must obfuscate any API keys, yet this one gets shown clear as day. More to do...

```
Removing orphaned /config/solcast-sites-TuWp12pVZ2yy8bB33BqrCb7pgk--******_n6X.json
Removing orphaned /config/solcast-usage-TuWp12pVZ2yy8bB33BqrCb7pgk--******_n6X.json
```

**Comment by Duncan1106** [comment]
![Screenshot_2025-04-09-21-44-02-698_io.homeassistant.companion.android-edit.jpg](https://github.com/user-attachments/assets/fdb94476-afe6-4049-b325-498bf8e4f8ac)

Just a quick follow up, the upper three are from forecast solar and the next three from solcast and the last the actual production from today. 

Yesterday and today solcast was more accurate than the base forecast solar from Homeassistant so I would say I'll switch to solcast completely.
I'm also very excited about the new site exclusion feature for the energy dashboard.

Great work 👍🏻
